---

- name: Enable reboot on kernel panic on Linux hosts
  sysctl:
    name: "kernel.panic"
    value: 5
    sysctl_set: yes
    state: present
    reload: yes
  when: ansible_distribution in ['Debian', 'Ubuntu']

- include: debian_install_packages.yml
  when: ansible_distribution == 'Debian'

- include: hosts.yml
- include: users_groups.yml

- include: locales.yml
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Create IRMA data directories
  file:
    path: "{{ item }}"
    owner: "{{ irma_user }}"
    group: "{{ irma_group }}"
    mode: 0755
    state: directory
  become: yes
  with_items:
    - /var/log/irma
    - /var/irma

- name: Create IRMA application directories
  file:
    path: "{{ item }}"
    owner: "{{ irma_user }}"
    group: "{{ irma_server_group }}"
    mode: 0750
    state: directory
  become: yes
  with_items:
    - /opt/irma

# Only for Demo boxes
- name: update python packages (download issue) for demo box
  pip:
    name: "{{ item }}"
    state: latest
    extra_args: "{{ pip_extra_args | default('') }}"
  with_items:
    - pip
    # to solve the following issue: https://github.com/Supervisor/meld3/issues/23
    - setuptools
  become: yes
  when: build_environment|default("default") == "demo"

- name: add a fancy message to the box
  copy:
    src: rc.local
    dest: /etc/rc.local
    owner: root
    group: root
    mode: 0644
  when: build_environment|default("default") == "demo"

- name: check if virtualbox vbguest are installed
  shell: "find /opt/VBoxGuestAdditions-* -name uninstall.sh | sh"
  become: yes
  when: build_environment|default("default") == "demo"
