---

- name: eScan | Check version
  command: escan --version
  ignore_errors: yes
  register: escan_present

- include: install.yml
  when: escan_present | failed

- name: eScan | Download latest definition files
  command: escan -xs --update
  become: yes
