language: python
python:
  - "2.7"

install: 
  - pip install -r requirements.txt

before_script:
  - sudo mkdir -p /var/log/irma/ && sudo touch /var/log/irma/sqlalchemy.log && sudo chmod 555 /var/log/irma/sqlalchemy.log
  - export IRMA_FRONTEND_CFG_PATH=tests/

script: 
  - nosetests tests/

notifications:
  email:
    on_success: never