---

- name: Dr Web | Checking licence file
  fail:
    msg: "Please ensure that 'drweb_license_file' is set in your host_vars or group_vars"
  when: drweb_license_file is not defined

- name: Dr Web | Installing license key
  copy:
    src: "{{ drweb_license_file }}"
    dest: /etc/opt/drweb.com
    owner: root
    group: root
    mode: 0644
  become: yes
  notify:
    - Restart DrWeb Daemon

- name: Configure DrWeb ini file
  ini_file:
    dest: /etc/opt/drweb.com/drweb.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    owner: root
    group: root
    mode: 0755
  become: yes
  notify: Restart DrWeb Daemon
  with_items: drweb_configs
