---

servers:
  - name: frontend.irma
    ip: 172.16.1.30
    ansible_groups: [frontend, sql-server]
    box: quarkslab/debian-9.0.0-amd64
    cpus: 2
    memory: 2048
    shares:
      - share_from: ../frontend
        share_to: /opt/irma/irma-frontend/releases/sync
        share_exclude:
          - .git/
          - venv/
          - web/dist
          - web/node_modules
      - share_from: ../common
        share_to: /opt/irma/irma-common/releases/sync
        share_exclude:
          - .git/
          - venv/
  - name: brain.irma
    ip: 172.16.1.31
    ansible_groups: [brain]
    box: quarkslab/debian-9.0.0-amd64
    cpus: 2
    memory: 2048
    shares:
      - share_from: ../brain
        share_to: /opt/irma/irma-brain/releases/sync
        share_exclude:
          - .git/
          - venv/
          - db/
      - share_from: ../common
        share_to: /opt/irma/irma-common/releases/sync
        share_exclude:
          - .git/
          - venv/
  - name: avs-linux.irma
    ip: 172.16.1.32
    ansible_groups: [eicar, trid]
    box: quarkslab/debian-9.0.0-amd64
    cpus: 2
    memory: 2048
    shares:
      - share_from: ../probe
        share_to: /opt/irma/irma-probe/releases/sync
        share_exclude:
          - .git/
          - venv/
      - share_from: ../common
        share_to: /opt/irma/irma-common/releases/sync
        share_exclude:
          - .git/
          - venv/

libvirt_config:
  driver: kvm
  # connect_via_ssh: true
  # host:
  # username:
  # storage_pool_name:
  # id_ssh_key_file:

ansible_vars:
  irma_environment: development
  vagrant: true
