---

- name: Zoner | Create temporary work dir
  file:
    path: "{{ zoner_temp_dir }}/"
    state: directory

- name: Zoner | Download Package
  get_url:
    url: "{{ zoner_url }}"
    dest: "{{ zoner_temp_dir }}/zav.deb"

- name: Zoner | Run installer
  apt:
    deb: "{{ zoner_temp_dir }}/zav.deb"
  sudo: yes

- name: Zoner | Remove temporary work dir
  file:
    path: "{{ zoner_temp_dir }}/"
    state: absent
