---

- include: debian_install_packages.yml
  when: ansible_distribution == 'Debian'

- include: hosts.yml
- include: users_groups.yml

- name: Create IRMA data directories
  file:
    path: "{{ item }}"
    owner: "{{ irma_user }}"
    group: "{{ irma_group }}"
    mode: 0755
    state: directory
  sudo: yes
  with_items:
    - /var/log/irma
    - /var/irma

- name: Create IRMA application directories
  file:
    path: "{{ item }}"
    owner: "{{ irma_user }}"
    group: "{{ irma_server_group }}"
    mode: 0750
    state: directory
  sudo: yes
  with_items:
    - /opt/irma

# Only for Demo boxes
- name: add a fancy message to the box
  copy:
    src: rc.local
    dest: /etc/rc.local
    owner: root
    group: root
    mode: 755
  when: build_environment|default("default") == "demo"
