---

- set_fact:
    probe_deployment_dir: "{{ probe_project_dir }}/{{ 'current' if irma_deployment_code_version == 'local' else 'releases/' + irma_deployment_release_name }}"

# Install Probe
- include: probe_deployment.yml

# Generate documentation
- include: sphinx.yml
  when: "'frontend-demo' in group_names"

# Configure (enventually) VirusTotal module
#
# ref: https://github.com/quarkslab/irma-ansible/pull/8
- include: modules_configurations.yml
  when: "'virustotal' in group_names"

- name: Restart Supervisor services
  supervisorctl:
    name: "{{ item.name }}"
    state: restarted
  sudo: yes
  with_items: supervisor_programs_probe
