---

- include: linux/provisioning_probe.yml
  when: "ansible_distribution in ['Debian', 'Ubuntu']"
  sudo: yes

- include: windows/provisioning_probe.yml
  when: "'Windows' in ansible_distribution"
  sudo: no

# vim: sw=2
