---

## Global
probe_user: "{{ default_user }}"
probe_group: "{{ default_group }}"

irma_install_dir_linux: /opt/irma
irma_install_dir_windows: C:/IRMA
irma_install_dir: "{{ irma_install_dir_linux if 'Windows' not in ansible_distribution else irma_install_dir_windows }}"

probe_project_dir: "{{ irma_install_dir }}/irma-probe"
probe_install_dir: "{{ probe_project_dir }}/current"
probe_venv_dir: "{{ probe_install_dir }}/venv"


## Deployment
probe_deployment_configs:
  - section: broker_probe
    option: host
    value: "{{irma_configurations.brain_addr}}"
  - section: broker_probe
    option: vhost
    value: "{{irma_configurations.rabbitmq.probe.vhost}}"
  - section: broker_probe
    option: username
    value: "{{irma_configurations.rabbitmq.probe.user}}"
  - section: broker_probe
    option: password
    value: "{{irma_configurations.rabbitmq.probe.password}}"
  - section: broker_brain
    option: host
    value: "{{irma_configurations.brain_addr}}"
  - section: broker_brain
    option: vhost
    value: "{{irma_configurations.rabbitmq.brain.vhost}}"
  - section: broker_brain
    option: username
    value: "{{irma_configurations.rabbitmq.brain.user}}"
  - section: broker_brain
    option: password
    value: "{{irma_configurations.rabbitmq.brain.password}}"
  - section: ftp_brain
    option: host
    value: "{{irma_configurations.brain_addr}}"
  - section: ftp_brain
    option: username
    value: "{{irma_configurations.ftpd.probe.username}}"
  - section: ftp_brain
    option: password
    value: "{{irma_configurations.ftpd.probe.password}}"

## Supervisor Role
supervisor_programs_probe:
  - name: probe_app
    command: "{{ probe_venv_dir }}/bin/celery worker -A probe.tasks --hostname=probe_app.%%h {{default_celery_options}}"
    directory: "{{ probe_install_dir }}"
    user: "{{ irma_user }}"
    numprocs: 1
    stdout_logfile: /var/log/supervisor/probe_app.log
    stderr_logfile: /var/log/supervisor/probe_app.log
    autostart: true
    stopwaitsecs: 600
    killasgroup: true

# VirusTotal module configuration
# Uncomment this to share an apikey to all virustotal probes
# virustotal_configs:
#   - section: VirusTotal
#     option: private
#     value: False
#   - section: VirusTotal
#     option: apikey
#     value: 88eb8e2f869e98ea9b0367cb47c143cb438a5e8d8dfd3b6e3fb6c898374b8fb6

# Bit Defender Scanner key - Put your licence key here
# bitdefender_scanner_key:

# Zoner Antivirus - put you licence key here
# zoner_license_key: XXXXX-XXXXX-XXXXX-XXXXX-XXXXX

# DrWeb Antivirus - put your configurations there
# drweb_configs:
#   - section: LinuxSpider
#     option: Start
#     value: No
# drweb_license_file: files/drweb32.key

# Avast! licence file - Put your licence file here
# avast_license_file: files/license.avastlic

# Sophos Antivirus Antivirus for Linux (Free) - Put your variables here
# sophos_archive_name: sav-linux-free-9.9.tgz
# sophos_update_username: ABCDEFGH
# sophos_update_password: 01s21z54ee
