---

- src: https://github.com/quarkslab/postgresql.git
  version: cb93aeb54ac8b6667a0c3ec7e9b18bda9b0c923c
  name: ANXS.postgresql

- src: https://github.com/weareinteractive/ansible-sudo.git
  version: 1.6.1
  name: franklinkim.sudo

- src: https://github.com/weareinteractive/ansible-ufw.git
  version: 1.6.0
  name: franklinkim.ufw

- src: https://github.com/jdauphant/ansible-role-nginx.git
  version: v2.7.4
  name: jdauphant.nginx

- src: https://github.com/quarkslab/ansible-playbook-rabbitmq.git
  version: 30ba105a753bb21eed07c8fa4b2635ff297b54b9
  name: Mayeu.RabbitMQ

- src: https://github.com/mivok/ansible-users.git
  version: v1.2.4
  name: mivok0.users

- src: https://github.com/willshersystems/ansible-sshd.git
  version: v0.4.7
  name: willshersystems.sshd
