---

- include: windows_install_packages.yml
- include: windows_configuration.yml


- name: Create IRMA application directories
  win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ irma_install_dir }}"

# vim: sw=2
