---

- name: VBA32 | Adding i386 repositories
  command: dpkg --add-architecture i386
  sudo: yes

- name: VBA32 | Install dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 0         # force refresh for i386 arch
  become: yes
  with_items:
    - libc6-i386
    - libstdc++6

- name: VBA32 | Check version
  command: /opt/vba/vbacl/vbacl
  args:
    chdir: /opt/vba/vbacl
  ignore_errors: yes
  register: virusblokada_present

- include: install.yml
  when: virusblokada_present | failed

- name: VBA32 | Update definition files
  shell: /opt/vba/vbacl/vbaupdx "{{ virusblokada_update_url }}"
  args:
    chdir: /opt/vba/vbacl
  become: yes
