---

- name: Ensure that directory /var/www has www-data rights
  file:
    path: /var/www
    state: directory
    owner: "{{ frontend_user }}"
    group: "{{ frontend_group }}"
    recurse: yes
  notify: restart nginx

# Open additional network ports on the Frontend
- name: Allow all access to HTTP
  ufw:
    rule: allow 
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 80
    - 443
  tags:
    - ufw

- include: openssl_configuration.yml
  when: frontend_openssl|default(False) == True
