---

- name: Ensure that directory /var/www has www-data rights
  file:
    path: /var/www
    state: directory
    owner: "{{ frontend_user }}"
    group: "{{ frontend_group }}"
    recurse: yes
  notify: restart nginx

- name: Install tools for PostgreSQL support
  apt:
    name: "postgresql-server-dev-{{postgresql_version}}"
    state: present

- pip:
    name: psycopg2
    state: present

- include: openssl_configuration.yml
  when: frontend_openssl|default(False) == True

# vim: sw=2
